
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BikeStore.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Bikes
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Bikes()
    {

        this.Bikes_Orders = new HashSet<Bikes_Orders>();

    }


    public int Id { get; set; }

    public string Manufacturer { get; set; }

    public string Type { get; set; }

    public string Description { get; set; }

    public string Preview { get; set; }

    public Nullable<int> Year { get; set; }

    public Nullable<double> Transmission { get; set; }

    public Nullable<double> Price { get; set; }

    public Nullable<double> Wheels { get; set; }

    public Nullable<double> Weight { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Bikes_Orders> Bikes_Orders { get; set; }

}

}
