
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BikeStore.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Bikes_Orders
{

    public int BikeId { get; set; }

    public int OrderId { get; set; }

    public int Quantity { get; set; }



    public virtual Bikes Bikes { get; set; }

    public virtual Orders Orders { get; set; }

}

}
