

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BikeStore.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DatabaseShopEntities1 : DbContext
{
    public DatabaseShopEntities1()
        : base("name=DatabaseShopEntities1")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Bikes> Bikes { get; set; }

    public virtual DbSet<Orders> Orders { get; set; }

    public virtual DbSet<Bikes_Orders> Bikes_Orders { get; set; }

}

}

